databases:
  - name: cadosLearn_api
    databaseName: cadosLearn_api
    user: cadoslearn_api_user

services:
  - type: web
    name: cadosLearn_api
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn cados_api.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cadosLearn_api
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4